apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow-dev

resources:
  - namespace.yaml

helmCharts:
  - name: airflow
    repo: https://airflow.apache.org
    version: 1.11.0
    releaseName: airflow
    valuesFile: values.yaml