executor: CeleryExecutor

webserver:
  service:
    type: ClusterIP

scheduler:
  replicas: 1

workers:
  replicas: 1

postgresql:
  image:
    repository: bitnamilegacy/postgresql
    tag: 15

dags:
  persistence:
    enabled: false
